version: '3'

services:
  db:
    image: 'mariadb:${MARIADB_VERSION:-10.7.3-focal}'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
      MYSQL_DATABASE: '${DB_DATABASE:-dolibarr}'
      MYSQL_USER: '${DB_USERNAME:-dolibarr}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-dolibarr}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - db:/var/lib/mysql
    networks:
      - dolibarr
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-p${DB_PASSWORD:-root}' ]
      retries: 3
      timeout: 5s

  php:
    image: voldlu/dolibarr-php:16.0.4
    environment:
      APP_URL: 'http://dolibarr.local'
      APP_DATABASE_HOST: 'db'
      APP_DATABASE_NAME: '${DB_DATABASE:-dolibarr}'
      APP_DATABASE_USER: '${DB_USERNAME:-dolibarr}'
      APP_DATABASE_PASS: '${DB_PASSWORD:-dolibarr}'
    networks:
      - dolibarr

  web:
    image: voldlu/dolibarr-nginx:16.0.4
    ports:
      - '${FORWARD_WEB_PORT:-80}:80'
    networks:
      - dolibarr

networks:
  dolibarr:
    driver: bridge

volumes:
  db:
    driver: local
